apiVersion: apps/v1
kind: Deployment
metadata:
  name: cinematicket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-react-app
  template:
    metadata:
      labels:
        app: my-react-app
    spec:
      containers:
        - name: my-react-app
          image: leoncana10/cinema-front
          ports:
            - containerPort: 3000